### PR TITLE
Allow setting json_encode options when calling getJson()

### PR DESCRIPTION
**Pull request by fayway**
So we can customize the returned JSON using the native json_encode options http://php.net/manual/en/function.json-encode.php

Example: 
`$jsonObj->getJson( JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT )`

### CODE REVIEW

**Comment by Galbar** [comment]
Interesting, I didn't know about this. It looks useful! 😃 

Just a few things before merging it, mainly about style to keep it consistent:
 * Remove the `.idea` line from the `.gitignore` file
 * Change `$options = 0` to `$options=0` (no spaces)
 * Change the comment in `getJson()` to look like below
```
    /**
     * Returns the json object encoded as string.
     * See http://php.net/manual/en/json.constants.php for more information on the $options bitmask.
     *
     * @param int $options json_encode options bitmask
     *
     * @return string
     */
```

Finally, add testing for the new behaviour. One unit test should suffice.

Thank you for your contribution!

**Comment by fayway** [comment]
Oops, the failed travis job pointed out to me that many json constants were introduced starting from specific PHP versions like JSON_PRETTY_PRINT and JSON_UNESCAPED_UNICODE available only since 5.4.0 
http://php.net/manual/en/json.constants.php

What do you suggest in this case?

**Comment by Galbar** [comment]
Looks good!

I just realized that Travis CI dropped support for PHP 5.3 in the past 28 days. 🤦‍♂️ 

What I'm going to do is drop support for 5.3 in the library and then you can merge master to your branch and then we can merge your branch into master.

It's become more complicated than I'd like it to be, sorry.

I'll let you know when you can merge from master 😃 
In the meanwhile you can drop the test for PHP 5.3

**Comment by Galbar** [comment]
I just merged into master a branch that drops php 5.3. If you take those changes into your branch all tests should pass. Remeber to remove the one for 5.3

**Comment by fayway** [comment]
Done 😊

**Comment by Galbar** [comment]
Looks good. sorry for not answering before, I've been busy.

Thanks for your contribution!

**Pull request merged**
